api/urls.py
from django.urls import path, include
from rest_framework import routers
from api.views import ProductModelViewSet, CategoryModelViewSet, BasketModelViewSet

app_name = 'api'

router = routers.DefaultRouter()
router.register(r'products_api', ProductModelViewSet)
router.register(r'categories_api', CategoryModelViewSet)
router.register(r'baskets_api', BasketModelViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

products/urls.py
from django.urls import path
from . import views as v
from .views import AddNewProduct, UpdateProduct

app_name = 'products'

urlpatterns = [
    path('', v.index, name='index'),
    path('category/<int:category_id>/', v.category, name='category'),
    # path('search/', SearchResultsView.as_view(), name='search'),
    path('search/', v.search_product, name='search'),
    path('basket/', v.basket, name='basket'),
    path('basket/add/<int:product_id>/', v.basket_add, name='basket_add'),
    path('basket/remove/<int:basket_id>/',
         v.basket_remove,
         name='basket_remove'),
    path('create_product/', AddNewProduct.as_view(), name='create_product'),
    path('edit_product/<int:pk>',
         UpdateProduct.as_view(),
         name='edit_product'),
    path('delete_product/<int:product_id>',
         v.delete_product,
         name='delete_product'),
]

store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from debug_toolbar.toolbar import debug_toolbar_urls
from rest_framework.authtoken.views import obtain_auth_token


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('users/', include('users.urls')),
    path('accounts/', include('allauth.urls')),
    path('api/', include('api.urls')),
    path('api-token-auth/', obtain_auth_token),
]

if settings.DEBUG:
    urlpatterns += debug_toolbar_urls()
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

# Ошибки
handler404 = 'products.views.error404'
CSRF_FAILURE_VIEW = 'products.views.error403'
handler500 = 'products.views.error500'

products/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class ProductCategory(models.Model):
    name = models.CharField(max_length=128)
    description = models.TextField(null=True,
                                   blank=True)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField()
    price = models.DecimalField(max_digits=6,
                                decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='products_images',
                              null=True,
                              blank=True)
    category = models.ForeignKey(to=ProductCategory,
                                 on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return f'Продукт: {self.name} | Категория: {self.category.name}'


class BasketQuerySet(models.QuerySet):
    def total_sum(self):
        return sum(basket.sum() for basket in self)

    def total_quantity(self):
        return sum(basket.quantity for basket in self)


class Basket(models.Model):
    user = models.ForeignKey(to=User,
                             on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product,
                                on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    objects = BasketQuerySet.as_manager()

    def __str__(self):
        return f'Корзина для {self.user.email} | Продукт: {self.product.name}'

    def sum(self):
        return self.product.price*self.quantity

products/forms.py
from django import forms
from products.models import Product


class AddProductForm(forms.ModelForm):
    class Meta():
        model = Product
        fields = '__all__'
        widgets = {
            'description': forms.Textarea(attrs={'rows': 4,
                                                 'cols': 15}),
        }

    def clean_image(self):
        image = self.cleaned_data['image']
        return image


class EditProductForm(forms.ModelForm):
    class Meta():
        model = Product
        fields = '__all__'
        widgets = {
            'description': forms.Textarea(attrs={'rows': 4,
                                                 'cols': 15}),
        }

    def clean_image(self):
        image = self.cleaned_data['image']
        return image

products/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.shortcuts import HttpResponseRedirect
from django.core.paginator import Paginator
from products.models import Product, Basket, ProductCategory
from django.contrib.auth import get_user_model
from django.db.models import Q
from products.forms import AddProductForm, EditProductForm
from django.views.generic import CreateView, UpdateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin


User = get_user_model()


def index(request):
    all_categories = ProductCategory.objects.all()
    all_products = Product.objects.order_by('id')
    paginator = Paginator(all_products, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request,
                  'products/index.html',
                  context={'categories': all_categories,
                           'page_obj': page_obj,
                           'title': 'Главная страница'})


def category(request, category_id):
    all_categories = ProductCategory.objects.all()
    all_products_category = Product.objects.filter(category_id=category_id)
    paginator = Paginator(all_products_category, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request,
                  'products/category.html',
                  context={'categories': all_categories,
                           'page_obj': page_obj})


def search_product(request):
    categories = ProductCategory.objects.all()
    query = request.GET.get('q')
    object_list = Product.objects.filter(Q(name__icontains=query))
    return render(request,
                  'products/index.html',
                  context={'object_list': object_list,
                           'categories': categories})

# class SearchResultsView(ListView):
#     model = Product
#     template_name = 'products/index.html'
#     title = 'Поиск'

#     def get_queryset(self):
#         query = self.request.GET.get('q')
#         categories = ProductCategory.objects.all()
#         object_list = Product.objects.filter(Q(name__icontains=query))
#         return object_list, categories


@login_required
def basket(request):
    products = Basket.objects.filter(user=request.user)
    return render(request,
                  'products/basket.html',
                  context={'products_in_basket': products,
                           'title': 'Корзина'})


@login_required
def basket_add(request, product_id):
    product = Product.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=request.user,
                                    product=product)
    if not baskets.exists():
        Basket.objects.create(user=request.user,
                              product=product,
                              quantity=1)
    else:
        basket = baskets.first()
        basket.quantity += 1
        basket.save()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def basket_remove(request, basket_id):
    baskets = Basket.objects.filter(id=basket_id,
                                    user=request.user)
    baskets.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


class AddNewProduct(LoginRequiredMixin, CreateView):
    model = Product
    form_class = AddProductForm
    template_name = 'products/add_product.html'
    success_url = reverse_lazy('products:index')


class UpdateProduct(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = EditProductForm
    template_name = 'products/edit_product.html'
    success_url = reverse_lazy('products:index')


# @login_required
# def create_product(request):
#     form = AddProductForm(request.POST or None, request.FILES)
#     context = {'form': form}
#     if form.is_valid():
#         instance = form.save(commit=False)
#         instance.save()
#         return redirect('products:index')
#     return render(request, 'products/add_product.html', context)


@login_required
def delete_product(request, product_id):
    product = get_object_or_404(Product,
                                id=product_id)
    product.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def error404(request, exception):
    return render(request,
                  'errors/404.html',
                  status=404)


def error403(request, reason=''):
    return render(request,
                  'errors/403.html',
                  status=403)


def error500(request):
    return render(request,
                  'errors/500.html',
                  status=500)

templates/products/add_product.html
{% extends "base.html" %}
{% load socialaccount %}
{% load static %}

{%block content%}
  <div class='container_form'>
    <h3>Добавление товара</h3>
    <div class='container_form_login'>
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
      </form>
    
  </div>
  </div>
{%endblock%}

templates/products/basket.html
{% extends "base.html" %}
{%block content%}
   {% if products_in_basket %}
   <h4>Общая сумма к оплате: {{products_in_basket.total_sum}}</h4>
   <h4>Число товаров: {{products_in_basket.total_quantity}}</h4>
        {% for product in products_in_basket %}
            <div class='recipe-container'><hr>
            <div class='one-recipe'>
            <li>Наименование: {{product.product.name}}</li>
            <li>Категория: {{product.product.category}}</li>
            <li>Описание: {{product.product.description}}</li>
            <li>Цена: {{product.product.price}}</li>
            {% if product.product.image %}<img src="{{product.product.image.url}}" height=10% width=10%>{%endif%}
            <li>Количество товара:{{product.quantity}}</li>
            <li>Общая стоимость товара: {{product.sum}}</li>
            <li><a href="{% url 'products:basket_remove' product.id%}">Убрать товар из корзины</a></li>
            </div>
            </div>
        {%endfor%}
    {%else%}
        <h4>Корзина пуста</h4>
    {%endif%}
{%endblock%}

templates/products/category.html
{% extends "base.html" %}
{%load static%}
{% block title %}
  <title>Главная страница</title>
{% endblock %}

{%block content%}
  <div class='categories'>
    <h4>Категории</h4>
    {%for category in categories %}
      <li><a href="{% url 'products:category' category.id%}">{{category.name}}</a></li>
    {%endfor%}
  </div>
  <div class='paginator-up'>
    {% include "includes/paginator.html" %}
  </div>
  {% for product in page_obj %}
    <div class='recipe-container'><hr>
      <div class='one-recipe'>
        <li>Наименование: {{product.name}}</li>
        <li>Описание: {{product.description}}</li>
        <li>Цена: {{product.price}}</li>
        {% if product.image %}<img src="{{product.image.url}}" height=10% width=10%>{%endif%}
          <li><a href="{% url 'products:basket_add' product.id%}">Добавить в корзину</a></li>
        {%if request.user.is_staff %}
          <li><a href="{% url 'products:edit_product' product.id%}">Редактировать товар</a></li>
          <li><a href="{% url 'products:delete_product' product.id%}">Удалить товар</a></li>
        {%endif%}
      </div>
    </div>
  {%endfor%}
  <div class='paginator-down'>
    {% include "includes/paginator.html" %}
  </div>
{%endblock%}

templates/products/edit_product.html
{% extends "base.html" %}
{% load socialaccount %}
{% load static %}

{%block content%}
  <div class='container_form'>
    <h3>Редактирование товара</h3>
    <div class='container_form_login'>
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
      </form>
    
  </div>
  </div>
{%endblock%}

templates/products/index.html
{% extends "base.html" %}
{%load static%}


{%block content%}
  <div class='categories'>
    <h4>Категории</h4>
    {%for category in categories %}
      <li><a href="{% url 'products:category' category.id%}">{{category.name}}</a></li>
    {%endfor%}
  </div>
  <div class='paginator-up'>
    {% include "includes/paginator.html" %}
  </div>
  {%if object_list %}
    {% for product in object_list %}
      <div class='recipe-container'><hr>
        <div class='one-recipe'>
          <li>Наименование: {{product.name}}</li>
          <li>Категория: {{product.category}}</li>
          <li>Описание: {{product.description}}</li>
          <li>Цена: {{product.price}}</li>
          {% if product.image %}<img src="{{product.image.url}}" height=10% width=10%>{%endif%}
          {%if request.user.is_authenticated%}
            <li><a href="{% url 'products:basket_add' product.id%}">Добавить в корзину</a></li>
            {%if request.user.is_staff %}
              <li><a href="{% url 'products:edit_product' product.id%}">Редактировать товар</a></li>
              <li><a href="{% url 'products:delete_product' product.id%}">Удалить товар</a></li>
            {%endif%}
          {%else%}
            Зарегистрируйтесь или войдите в аккаунт, чтобы добавлять продукты в корзину
          {%endif%}
        </div>
      </div>
    {%endfor%}
  {%else%}
    {% for product in page_obj %}
      <div class='recipe-container'><hr>
        <div class='one-recipe'>
          <li>Наименование: {{product.name}}</li>
          <li>Категория: {{product.category}}</li>
          <li>Описание: {{product.description}}</li>
          <li>Цена: {{product.price}}</li>
          {% if product.image %}<img src="{{product.image.url}}" height=10% width=10%>{%endif%}
          <li>
            {%if request.user.is_authenticated%}
              <a href="{% url 'products:basket_add' product.id%}">Добавить в корзину</a>
            {%else%}
              Зарегистрируйтесь или войдите в аккаунт, чтобы добавлять продукты в корзину
            {%endif%}
          </li>
          {%if request.user.is_staff %}
            <li><a href="{% url 'products:edit_product' product.id%}">Редактировать товар</a></li>
            <li><a href="{% url 'products:delete_product' product.id%}">Удалить товар</a></li>
          {%endif%}
        </div>
      </div>
    {%endfor%}
  {%endif%}
    <div class='paginator-down'>
      {% include "includes/paginator.html" %}
    </div>
{%endblock%}