api/urls.py
from django.urls import path, include
from rest_framework import routers
from api.views import ProductModelViewSet, CategoryModelViewSet, BasketModelViewSet

app_name = 'api'

router = routers.DefaultRouter()
router.register(r'products_api', ProductModelViewSet)
router.register(r'categories_api', CategoryModelViewSet)
router.register(r'baskets_api', BasketModelViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

products/urls.py
from django.urls import path
from . import views as v
from .views import AddNewProduct, UpdateProduct

app_name = 'products'

urlpatterns = [
    path('', v.index, name='index'),
    path('category/<int:category_id>/', v.category, name='category'),
    # path('search/', SearchResultsView.as_view(), name='search'),
    path('search/', v.search_product, name='search'),
    path('basket/', v.basket, name='basket'),
    path('basket/add/<int:product_id>/', v.basket_add, name='basket_add'),
    path('basket/remove/<int:basket_id>/',
         v.basket_remove,
         name='basket_remove'),
    path('create_product/', AddNewProduct.as_view(), name='create_product'),
    path('edit_product/<int:pk>',
         UpdateProduct.as_view(),
         name='edit_product'),
    path('delete_product/<int:product_id>',
         v.delete_product,
         name='delete_product'),
]

store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from debug_toolbar.toolbar import debug_toolbar_urls
from rest_framework.authtoken.views import obtain_auth_token


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('users/', include('users.urls')),
    path('accounts/', include('allauth.urls')),
    path('api/', include('api.urls')),
    path('api-token-auth/', obtain_auth_token),
]

if settings.DEBUG:
    urlpatterns += debug_toolbar_urls()
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

# Ошибки
handler404 = 'products.views.error404'
CSRF_FAILURE_VIEW = 'products.views.error403'
handler500 = 'products.views.error500'

users/urls.py
from django.urls import path
from django.contrib.auth import views
from users import views as v
from .views import CustomLoginView, CustomLogoutView

app_name = 'users'

urlpatterns = [
    path('registration/', v.registration, name='registration'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('profile/change_password',
         views.PasswordChangeView.as_view(),
         name='password_change'),
    path('email/', v.contact_view, name='send_email_to_tp'),
    path('success/', v.success_view, name='success'),
    ]

templates/base.html
<!DOCTYPE html>
<html lang='ru'>
{%load static%}
<link rel='stylesheet' href='/static/css/stylesheet.сss' type="text/css">
  <head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/stylesheet.css' %}">
    {% comment %} <link rel='stylesheet' href='/static/css/stylesheet.сss' type="text/css"> {% endcomment %}
    {%block title%}
      <title>{{title}}</title>
    {%endblock%}
  </head>

  <body class='body'>
    <header class='header'>
      <div class='container_emblem'>
        <a href="{% url 'products:index'%}"><img class='emblem' src="{% static 'img/emblem.png' %}"></a></div>
      <div class='container_search'>
        <form action="{% url 'products:search' %}" method="get">
          <input name="q" type="text" placeholder="Поиск...">
          <input type="submit" value="Искать" />
        </form></div>
      <div class='container_buttons'>
        {%if request.user.is_authenticated%}
          <div class="dropdown">
            <button class="dropbtn">Настройки<i class="fa fa-caret-down"></i></button>
              <div class="dropdown-content">
                {%if request.user.is_staff %}
                <h5>Вы зашли как {{request.user.username}} "Модератор" </h5>
                <a href="{% url 'products:create_product'%}">Редактировать каталог</a>
                <a href="{% url 'products:basket'%}">Корзина</a>
                <a href="{% url 'users:password_change'%}">Поменять пароль</a>
                <a href="{% url 'users:send_email_to_tp'%}">Тех.поддержка</a>
                <a href="{% url 'users:logout'%}">Выход</a>
                {%else%}
                <h5>Вы зашли как {{request.user.username}}</h5>
                <a href="{% url 'products:basket'%}">Корзина</a>
                <a href="{% url 'users:password_change'%}">Поменять пароль</a>
                <a href="{% url 'users:send_email_to_tp'%}">Тех.поддержка</a>
                <a href="{% url 'users:logout'%}">Выход</a>
                {%endif%}
              </div>
          </div>
        {%else%}
          <a href="{% url 'users:login'%}"><button type='button' class='button_enter'>Войти</button></a>
          <a href="{% url 'users:registration'%}"><button type='button' class='button_register'>Регистрация</button></a>
        {%endif%}</div>
    </header>

    <main>
      <div class='cointeiner_content'>
        {% block content %}{% endblock %}
      </div>
    </main>
  </body>
</html>